source 'https://github.com/CocoaPods/Specs.git'

xcodeproj "CocoaOnePExample/CocoaOnePExample.xcodeproj"

pod "CocoaOneP", :path => "../CocoaOneP.podspec"
pod "Lockbox"

link_with 'CocoaOnePExample', 'CocoaOnePExampleTests'
