source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
xcodeproj "CocoaOnePExample/CocoaOnePExample.xcodeproj"

pod "CocoaOneP", :path => "../CocoaOneP.podspec"
pod "Lockbox"

link_with 'CocoaOnePExample', 'CocoaOnePExampleTests'

target 'CocoaOnePExampleTests' do
    pod 'OCMock', '~> 3.1'
end

#  vim: set ft=ruby sw=4 ts=4 :
