source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
xcodeproj "CocoaOnePExample/CocoaOnePExample.xcodeproj"

pod "CocoaOneP", :path => "../CocoaOneP.podspec"
pod "Lockbox"

link_with 'CocoaOnePExample', 'CocoaOnePExampleTests'

target 'CocoaOnePExampleTests' do
    pod 'OCMock', '~> 3.1'
end
